apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeus-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: zeus-ui
  template:
    metadata:
      labels:
        app: zeus-ui
    spec:
      containers:
      - image: need-to-add-the-image-name
        name: zeus-ui
        ports:
        - containerPort: 80
