apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: zeus
data:
  mongodb_username: some-username
  mongodb_password: some-password
  redis_username: some-username
  redis_password: some-password
